# permissions for end users to edit ingressmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ingress-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: ingressmanager-editor-role
rules:
- apiGroups:
  - operator.codehorse.com
  resources:
  - ingressmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.codehorse.com
  resources:
  - ingressmanagers/status
  verbs:
  - get
