apiVersion: operator.codehorse.com/v1beta1
kind: IngressManager
metadata:
  labels:
    app.kubernetes.io/name: ingress-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: ingressmanager-sample
spec:
  active: true
  startTime: "15:00"
  period: 1
  service:
    name: "svc-test"
    namespace: "default"
  ingress:
    name: "ingress-test"
    namespace: "default"
    className: "nginx"
    host: "codehorse.com"
    path: "/"
